version: '3.8'

services:
  react-app:
    container_name: react-app
    build:
      context: simple-logo-generator
      dockerfile: Dockerfile
    ports:
      - "8084:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  web:
    build: .
    ports:
      - "8082:80"
    depends_on:
      - react-app